name: Submit to IndexNow

on:
  schedule:
    - cron: '0 * * * *'   # Runs hourly
  workflow_dispatch:       # Allows manual triggering

permissions:
  contents: write          # Needed to push submitted.txt updates

jobs:
  indexnow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Run IndexNow submission
        run: ruby run.rb

      - name: Save submitted list
        run: |
          git config --global user.name "IndexNow Bot"
          git config --global user.email "indexnow@fischr.org"
          git add submitted.txt
          git commit -m "Update submitted list" || echo "No changes"
          git push