name: indexnow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *' # alle 12 Stunden ausführen

jobs:
  indexnow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Run IndexNow submission
        run: ruby run.rb

      - name: Save submitted list
        run: |
          git config --global user.name "IndexNow Bot"
          git config --global user.email "indexnow@example.com"
          git add .indexnow-submitted.txt
          git commit -m "Update submitted list" || echo "No changes to commit"
          git pull --rebase
          git push